import React from "react";

const InputField = ({
  name,
  label,
  type = "text",
  placeholder,
  notEdittable = false,
  isAutoGenerated = false,
  required = false,
  pattern = null,
  register,
  errors,
  value,
}) => {
  return (
    <label htmlFor={name} className="inter">
      <div className="flex flex-col gap-2">
        <h1 className="font-semibold">
          {label}{" "}
          {isAutoGenerated && (
            <span className="text-gray-500 text-sm font-normal">
              (Auto-Generated)
            </span>
          )}{" "}
          {required && <span className="text-red-500">*</span>}
        </h1>
        <div className="w-full">
          <input
            type={type}
            name={name}
            placeholder={placeholder}
            {...register(name, {
              required: required && `${label} is required`,
              pattern: pattern && {
                value: pattern,
                message: `Invalid ${label} format.`,
              },
            })}
            value={value}
            readOnly={notEdittable}
            className={`${
              errors[name] ? "border-[2px] border-red-500" : ""
            } h-[60px] border border-[#E2E8F0] outline-[#0C1E33] rounded-md px-4 w-full`}
            style={{ pointerEvents: notEdittable ? "none" : "auto" }}
          />
          {errors[name] && (
            <div className="text-red-500 font-semibold mt-2">
              {errors[name].message}
            </div>
          )}
        </div>
      </div>
    </label>
  );
};

export default InputField;
