import { useForm } from "react-hook-form";
import { toast } from "react-toastify";
import { FiMinus } from "react-icons/fi";
import { useDispatch } from "react-redux";
import { registerStudent } from "../../features/students/studentsSlice";
import { generateStudentID } from "../../utils/generateId";
import { useState } from "react";
import InputField from "../../components/InputField";

const StudentRegistrationForm = ({ toggleAddStudentState, onStudentAdded }) => {
  const dispatch = useDispatch();

  const [studentId, setStudentId] = useState(generateStudentID);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors, isSubmitting },
  } = useForm();

  const onSubmit = async (data) => {
    try {
      await dispatch(registerStudent(data)).unwrap();
      reset();
      setStudentId(generateStudentID());
      onStudentAdded();
      toggleAddStudentState();
    } catch (error) {
      console.error("Error:", error);
      toast.error("An error occurred. Please try again later.");
    }
  };

  return (
    <div className="overlay fixed inset-0 z-10 bg-[rgba(210,210,215,0.35)] backdrop-blur-[4px] transition-all duration-300 ">
      <div className="fixed-container z-20 h-[90vh] w-full overflow-y-scroll bg-white opacity-100 transition-all duration-300 md:w-[70%] md:border md:border-r-0 md:border-t-0 md:border-l-[#d2d2d7] lg:w-1/2 rounded-md">
        <div className="p-10 add-user__container">
          <div className="flex items-center justify-between">
            <h1 className="text-3xl play-regular uppercase ">Add Student</h1>
            <button
              onClick={toggleAddStudentState}
              className="bg-[#164e8e] text-white h-[40px] rounded-md  px-4 inter flex items-center justify-center gap-3"
            >
              Close
              <FiMinus size={26} />
            </button>
          </div>

          {/* ADMIN FORM */}
          <form
            onSubmit={handleSubmit(onSubmit)}
            className="flex flex-col gap-6 mt-10    "
          >
            <InputField
              name="username"
              label="Username"
              value={studentId}
              notEdittable
              isAutoGenerated
              register={register}
              errors={errors}
            />

            <InputField
              name="firstName"
              label="First Name"
              placeholder="First Name"
              required
              pattern={/^[a-zA-Z\s]+$/}
              register={register}
              errors={errors}
            />

            <InputField
              name="lastName"
              label="Last Name"
              placeholder="Last Name"
              required
              pattern={/^[a-zA-Z\s]+$/}
              register={register}
              errors={errors}
            />

            <label className="inter">
              <div className="flex flex-col gap-2">
                <div className="flex gap-1">
                  <h1 className="font-semibold">Gender</h1>
                  <span className="text-red-500">*</span>
                </div>
                <div className="flex items-center gap-4">
                  {["Male", "Female"].map((gender) => (
                    <label key={gender} className="flex items-center gap-2">
                      <input
                        type="radio"
                        value={gender}
                        name="gender"
                        {...register("gender", {
                          required: "Gender is required",
                        })}
                        className="h-5 w-5 text-blue-500"
                      />
                      <span>{gender}</span>
                    </label>
                  ))}
                </div>
                {errors.gender && (
                  <div className="text-red-500 font-semibold">
                    {errors.gender.message}
                  </div>
                )}
              </div>
            </label>

            <InputField
              name="email"
              label="Email Address"
              placeholder="Email Address"
              required
              pattern={/^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/}
              register={register}
              errors={errors}
            />

            <InputField
              name="birthday"
              label="Date of Birth"
              type="date"
              required
              register={register}
              errors={errors}
            />

            <InputField
              name="address"
              label="Address"
              placeholder="Address"
              required
              register={register}
              errors={errors}
            />

            <InputField
              name="phoneNumber"
              label="Phone Number"
              placeholder="09998271821"
              required
              register={register}
              errors={errors}
              pattern={/^\d+$/}
            />

            <div className="flex flex-col gap-4 ">
              <button
                disabled={isSubmitting}
                type="submit"
                className="bg-[#0C1E33] text-white h-[55px] rounded-md mt-2  inter flex items-center justify-center gap-3"
              >
                {isSubmitting ? (
                  <l-dot-pulse
                    size="38"
                    speed="1.3"
                    color="white"
                  ></l-dot-pulse>
                ) : (
                  <div className="flex items-center gap-3">
                    <span>Add Student</span>
                    <svg
                      width="18"
                      height="14"
                      viewBox="0 0 18 14"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M1 7H17M17 7L11 1M17 7L11 13"
                        stroke="white"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </div>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default StudentRegistrationForm;
